name: fixCode

on:
    push:
        branches:
            - main
            - dev/lutica
            
jobs:
    fixer :
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: '20'
        - name: Install dependencies
          run: npm install
        - name: Lint & fix
          run: npx eslint . --fix --ext .tsx --ext .ts
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v3
          with:
                branch: ${{ github.ref_name }}-autofix
                reviewers: ${{ github.actor }}
                labels: autofix
                delete-branch: true
                title: "Improve codestyle"
                body: "Automated PR to improve codestyle"