name: Deploy

on:
  push:
    branches:
      - main
      - dev/lutica

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Install dependencies2
        run: npm install
      - name: run test
        run: npm run test